### ISSUE TITLE
api dependencies are skipped if download error occurs

### ISSUE THREAD

**Issue by jschlatow** [nfeske/goa#10]
I tried to extend the unix shell a bit and noticed that some api archives are reported missing as soon as I run `goa publish`. I believe the api archives are automatically downloaded, however, if goa is unable to pull a certain archive once it seems to forget some dependencies.
I'm able to reproduce this issue with the following modifications on the `intro/unix_3rd` in [goa-playground](https://github.com/nfeske/goa-playground):
1. remove the `var` directory to start on a clean slate
2. add `alex-ab/src/which` to `pkg/unix_3rd/archives`
3. add `set version(alex-ab/src/which) 2021-02-22` to `.goarc`
4. run `goa add-depot-user alex-ab --depot-url https://depot.genode.org --pubkey-file /path/to/alex-ab/pubkey`
5. run `goa run` - this will fail on downloading https://depot.genode.org/alex-ab/api/libc/2021-02-22.tar.xz
6. run `goa run` again - this will succeed
7. yet, running `goa publish` will report a bunch of missing api archives

**Comment by nfeske** [comment]
The api archives are not needed for `goa run`. It is happy with the downloaded binaries. Hence, if the APIs (that were used to produce the downloaded binaries) are missing, goa does not complain in this step.

When publishing, however, all sources including the apis must be published, in particular to ensure the compliance to open-source licenses that require distributing software in a form that can actually be built. Hence the failure.

Now the question is, how can a user resolve this situation? Do you have an idea how goa could assist best?

**Comment by jschlatow** [comment]
What about adding a subcommand `goa download` for acquiring the missing archives (or integrate this into the publish subcommand)?

**Comment by nfeske** [comment]
I think the latter - attempting the download of missing APIs as part of the publish step - would be very convenient.

Would you like to give implementing this a try?

**Comment by jschlatow** [comment]
I'll have a look.

**Comment by jschlatow** [comment]
@nfeske I believe commit c1ea266 should suffice. It triggers the download of missing dependencies just before the actual publishing.

**Comment by nfeske** [comment]
That was quick! Thank you @jschlatow. Merged to master.
