### ISSUE TITLE
versions for `nfeske/src/linux_nic_drv` and `nfeske/src/lx_fs` missing

### ISSUE THREAD

**Issue by jschlatow** [nfeske/goa#12]
The packages are referenced in `share/goa/lib/run/linux.tcl` but missing in `share/goa/goarc`.

**Comment by nfeske** [comment]
I've updated the versions and published the corresponding packages but have not tested them. @jschlatow could you give the current master a try?

**Comment by jschlatow** [comment]
@nfeske I just noticed that my commit for the <rtc> requirement accidentally changed `nfeske/src/lx_fs` into `jschlatow/src/lx_fs` in `share/goa/lib/run/linux.tcl`. I missed that when reviewing my commit.

Apart from that I successfully tested your published packages.

Do you also want to provide the linux_rtc_drv package, which is now referenced in `share/goa/lib/run/linux.tcl`?

**Comment by nfeske** [comment]
Thanks for the notice. This should be fixed by commit https://github.com/nfeske/goa/commit/ecfa44145b5f6b2ba198e82ce92980bca0c33b7e

**Comment by jschlatow** [comment]
Perfect!
