### ISSUE TITLE
missing `used_apis` file in exported src recipe

### ISSUE THREAD

**Issue by jschlatow** [nfeske/goa#20]
If a Goa project has an empty `used_apis` file, the exported src recipe is missing the `used_apis` file. However, Genode's build system requires this file to be present when importing the recipe via `import_from_depot`.

**Comment by nfeske** [comment]
Thanks for the issue and the fix. It makes me curious. Can you share what kind of src project depends on no API?

**Comment by jschlatow** [comment]
Sure, this comes from src projects that create FPGA bitstreams. Naturally, a bitstream does not have any API dependency. Note that I have just added support for generating bitstreams with Vivado (PR #21). An example is provided in my [goa-pkg repository](https://github.com/jschlatow/goa-pkgs/tree/master/zynq/zybo_z720_gpio-bitstream).

**Comment by nfeske** [comment]
Thanks. I knew, there had to be a cool story behind it!
