### ISSUE TITLE
Add documentation of build systems

### ISSUE THREAD

**Issue by jschlatow** [nfeske/goa#22]
Since its release, Goa has been augmented with support for additional build systems (autoconf, qmake, vivado) that require some sort of user documentation.

**Comment by jschlatow** [comment]
@nfeske, commit 1ff1ac9 adds a first version of the "build-systems" man page.

**Comment by nfeske** [comment]
That's beautiful!

I merged your commit to staging along with the fixup https://github.com/nfeske/goa/commit/2856435b3d95382dfede1c8d5ca50aac073abb0b, if you don't mind.

**Comment by jschlatow** [comment]
Thanks! I don't mind the fixup :wink:
