### ISSUE TITLE
goa fails to find its directory when run via a relative symbolic link

### ISSUE THREAD

**Issue by NobodyIII** [nfeske/goa#4]
I know this isn't a huge deal, but when goa is run via a relative symbolic link, e.g. "../goa/bin/goa", it doesn't properly find its install directory. Either it should resolve relative links properly, or there should be a notice in the readme that goa cannot be added to the shell path via a relative symbolic link.

**Comment by nfeske** [comment]
Thanks for reporting. The issue should be fixed with commit https://github.com/nfeske/goa/commit/11f40f6a313e3fb67254baafe4faaa5409551117

@NobodyIII I'd appreciate a confirmation from your side.

**Comment by NobodyIII** [comment]
That fixes it.

**Comment by nfeske** [comment]
Thank you for the confirmation. :-)
