### ISSUE TITLE
error executing `goa build`

### ISSUE THREAD

**Issue by decaduto** [nfeske/goa#9]
Hello Norman,

Today I've installed your goa program, I've followed every step you described in your installation file, but every time I try to execute it,  (goa build), it appears the following error:

/usr/local/genode/tool/current/bin/genode-x86-gcc: 1: /usr/local/genode/tool/current/bin/genode-x86-gcc: Syntax error: "(" unexpected
    while executing
"exec $cross_dev_prefix\gcc -print-libgcc-file-name"
    (file "/home/sgrjlhgwl/goa/share/goa/lib/flags.tcl" line 14)
    invoked from within
"source [file join $tool_dir lib flags.tcl]"
    invoked from within
"if {$perform(build-dir)} {

	#
	# Prepare depot content for the used APIs and generate ABI stubs
	#
	# This must happen before assembling the compile ..."
    (file "/home/sgrjlhgwl/goa/bin/goa" line 495)

Honestly I don't know how I can fix it, any helps?

Thanks.

PS: I've installed everything needed: from Genode toolchain to expect  tool (& the other your wrote)

:)

**Comment by nfeske** [comment]
I'm closing this issue since you have taken this topic to the Genode mailing list.
